# Generated by Django 4.2 on 2023-04-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_pdf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf_1',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_2',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
