# Generated by Django 4.2 on 2023-04-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_pdf_1_post_pdf_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf_name',
        ),
    ]
